var redirects =  {
	'Installation_on_Windows': 'https://github.com/nzbget/nzbget/wiki/Installation-on-Windows',
	'Installation_on_Mac': 'https://github.com/nzbget/nzbget/wiki/Installation-on-Mac',
	'Installation_on_Linux': 'https://github.com/nzbget/nzbget/wiki/Installation-on-Linux',
	'Installation_on_POSIX': 'https://github.com/nzbget/nzbget/wiki/Installation-on-POSIX',
	'Build_the_latest_development_version_from_svn': 'https://github.com/nzbget/nzbget/wiki/Build-the-latest-development-version',
	'Cross_compiling': 'https://github.com/nzbget/nzbget/wiki/Cross-compiling',
	'Packaging': 'https://github.com/nzbget/nzbget/wiki/Packaging',
	'Performance_tips': 'https://github.com/nzbget/nzbget/wiki/Performance-tips',
	'Choosing_a_cipher': 'https://github.com/nzbget/nzbget/wiki/Choosing-cipher',
	'NZBGet_behind_other_web-server': 'https://github.com/nzbget/nzbget/wiki/NZBGet-behind-other-web-server',
	'Catalog_of_post-processing_scripts': 'https://github.com/nzbget/nzbget/wiki/Catalog-of-post-processing-scripts',
	'RSS': 'https://github.com/nzbget/nzbget/wiki/RSS',
	'VideoSort': 'https://github.com/nzbget/VideoSort',
	'Command_line_reference': 'https://github.com/nzbget/nzbget/wiki/Command-line-reference',
	'Extension_scripts': 'https://github.com/nzbget/nzbget/wiki/Extension-scripts',
	'RPC_API_reference': 'https://github.com/nzbget/nzbget/wiki/API',
	'History_(ChangeLog)': 'https://github.com/nzbget/nzbget/releases',
	'Documentation': 'https://github.com/nzbget/nzbget/wiki',
	'documentation': 'https://github.com/nzbget/nzbget/wiki',
	'donation': 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7NCAT7FDRSH5C',
	'history': 'https://github.com/nzbget/nzbget/releases',
	'forum': 'http://nzbget.net/forum/index.php',
};
